name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Jest
        run: npm install jest --save-dev
        
      - name: Run Tests
        run: npx jest
      - name: Notify n8n on Failure
        if: failure()
        run: |
          curl -X POST "https://heterofermentative-unbleeding-jutta.ngrok-free.dev/webhook/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" \
          -H "Content-Type: application/json" \
          -d '{"status": "failed", "msg": "Erreur f GitHub Actions!"}'
